from hms.models.base import Base  # noqa: F401
from hms.models.models import (  # noqa: F401
    Login,
    Admin,
    Student,
    Hostel,
    Room,
    Allocation,
    Fee,
    Bed,
    Setting,
    Payment,
    Settlement,
    MaintenanceRequest,
    FoodMenu,
    ACReading,
    ParentGuest,
    Announcement,
    Complaint,
    Visitor,
    Attendance,
    Leave,
    Staff,
)
